sonar.projectKey=DanielSchmerber_SQS26_MovieTracker
sonar.organization=danielschmerber

sonar.sources=backend/sqs-movietracker,frontend/sqs-movietracker/src
sonar.tests=backend/sqs-movietracker/tests
sonar.test.inclusions=backend/sqs-movietracker/tests/**/*.py

sonar.exclusions=backend/sqs-movietracker/tests/**,frontend/sqs-movietracker/src/routeTree.gen.ts,**/node_modules/**,**/.output/**
sonar.coverage.exclusions=backend/sqs-movietracker/tests/**,backend/sqs-movietracker/alembic/**,frontend/sqs-movietracker/src/**/*.tsx,frontend/sqs-movietracker/src/**/*.ts
sonar.python.coverage.reportPaths=backend/sqs-movietracker/coverage.xml
sonar.python.version=3.12
