"""replace_name_with_username_on_users

Revision ID: 6048f0526b82
Revises: cec9753b2a5b
Create Date: 2026-05-20 15:33:21.099146

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6048f0526b82'
down_revision: Union[str, Sequence[str], None] = 'cec9753b2a5b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('username', sa.String(length=50), nullable=False))
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.drop_column('users', 'name')
    op.create_index(op.f('ix_watchlist_movie_id'), 'watchlist', ['movie_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_watchlist_movie_id'), table_name='watchlist')
    op.add_column('users', sa.Column('name', sa.VARCHAR(length=50), nullable=False))
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_column('users', 'username')
    # ### end Alembic commands ###
